### PR TITLE
Fix broken urls

### PR DESCRIPTION
**Pull request by EverStarck**
https://ecss.info/ throws a 404

imagen

### CODE REVIEW

**Comment by emmacharp** [comment]
It works here. And since there is a french version, I do not want to send users specifically to the english one. There is a redirection based on the user's browser/os language and maybe it is broken.

What is your os/browser language?

**Comment by EverStarck** [comment]
> It works here. And since there is a french version, I do not want to send users specifically to the english one. There is a redirection based on the user's browser/os language and maybe it is broken.
> 
> What is your os/browser language?

ohh yeah you're right. I'm using a Spanish(es-MX) browser lang. If I change it to English it redirects fine to `/en`

**Comment by emmacharp** [comment]
You should be redirected to /en even with your os in spanish... I'll investigate further. Thanks for the catch!

**Comment by emmacharp** [comment]
Hi @EverStarck, can you confirm that you are now redirected when resquesting [ecss.info](https://ecss.info)?

**Comment by EverStarck** [comment]
yup @emmacharp, working like a charm 🔥 Thanks!

**Comment by emmacharp** [comment]
Thanks to you for the followup!

**Pull request closed without merging**
